### ISSUE TITLE
Testin Helios

### ISSUE THREAD

**Issue by elRaulito** [Hyperion-BT/Helios#1]
I really love Helios!!

I tried this contact and got an issue, maybe something is wrong:

`data Datum {
    king             PubKeyHash,
    hold             Value
}
func main(datum Datum, ctx ScriptContext) Bool {
    tx Tx = getTx(ctx);
    currentHash ValidatorHash = getCurrentValidatorHash(ctx);
    newKing PubKeyHash = head(getTxSignatories(tx)); 
    newValue Value = valueLockedBy(tx, currentHash); 
    newDatum Datum = Datum{
    king: newKing,
    hold: newValue
    };  
    refund Value = datum.hold;
    if((newValue>datum.hold)&&(valueSentTo(tx,datum.king)==refund)&&(isTxSignedBy(tx, newDatum.king)&&(valueLockedByDatum(tx, currentHash,newDatum)==newDatum.hold))){
    trace("perfect",true)
    }
    else{
    trace("not enough or refund not present",false)
    }
}`
But when I tried to unlock the utxo from the SC I got from the error:

`Caused by: [
  (force (force (builtin sndPair)))
  (con
    data
    #d8799f581c42f6f097db0e98e6c27dc604716d5cabd4f658d2dd5659e1a6bcf021a140a1401a00989680ff
  )
]
`

The data is the datum as input, probably an error when the contract  tried to access the value in the datum?

If you have any idea :)

otherwise don't worry, I will try again in the next days

**Comment by christianschmitz** [comment]
Thanks for helping us test Helios!

The `sndPair` function only works on pair type, not on data type.

So something didn't convert data properly into pair.

In the meantime we've made a lot of changes to Helios though, include major syntax improvements (https://github.com/Hyperion-BT/Helios/tree/dev). I just haven't merged these changes into the main branch yet because they haven't been debugged properly yet.

To help with debugging these kinds of issues I'm working on a step-by-step debugger. I should be able to put a first version of the debugger online this weekend. Note: it will only work with the latest syntax Helios (i.e. dev branch).

I invite you (and anyone else reading this) to our discord server for discussions and updates: https://discord.gg/fSAYtCAm

**Comment by christianschmitz** [comment]
I think I've found the problem in the compiler: the `MemberExpr` should receive a list-of-data type as it's left-hand-arg, and for some reason it didn't. But the latest version of Helios doesn't work like that anymore: everything is always kept as `data` (only converted back and forth to primitive types as needed by the builtins of plutus-core)

**Comment by christianschmitz** [comment]
I've merged the dev branch into main, so I'm going to close this issue as almost the whole compiler has since changed.
