### ISSUE TITLE
Need flag to turn off assert all unused variable

### ISSUE THREAD

**Issue by vh-zuka** [Hyperion-BT/Helios#11]
[https://github.com/Hyperion-BT/Helios/blob/35eb09c5d2bd2a0ab753be20744ff6865b40bf33/helios.js#L10582](https://l.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2FHyperion-BT%2FHelios%2Fblob%2F35eb09c5d2bd2a0ab753be20744ff6865b40bf33%2Fhelios.js%3Ffbclid%3DIwAR0DLL6q-wgy895egbwV4HnALIh3EzlymoIJOeeRDaQmlI5IL4C4KvWvzIg%23L10582&h=AT0ZsP3CMnQdka7mzPHUqmnttoXp7jusj7mBYU4N7C0B_L-Vm4sqm28Ugbs0s6U9aecg2i05wDGTsZpjtuJKc8ioh4Bni377Noq8duly20CGSzgXdoYW78_LyY-KPMh6k7-NsZd0Kx8)

Sometimes, we use datum to store configs of protocol and unuse these variables in the script.

**Comment by christianschmitz** [comment]
If the unused fields come last in the Datum struct then you can leave them out of Helios struct definition and the script will still work the same.

Structs are internally implemented as lists of generic data types, so anything at the end of a struct doesn't influence the fields at the start.

If you use Helios generators to create the datum data structure then I think that that shouldn't throw an *unused* error.

**Comment by sk-saru** [comment]
Could you create a discord channel for more conversation?

**Comment by christianschmitz** [comment]
Yes, you can join our discord: https://discord.gg/XTwPrvB25q

**Comment by sk-saru** [comment]
Thank you

**Comment by kk-hoangvd** [comment]
How about enabling unused variable by '_variableName'?

**Comment by christianschmitz** [comment]
> How about enabling unused variable by '_variableName'?

That's a good idea actually. I want to take some time to think about it though:
part of the design philosophy of Helios is to be as readable as possible. I'm afraid that allowing unused variables/fields, even with an underscore prefix, would make the final code less readable and thus a little more difficult to audit.

Perhaps it is OK to allow unused fields though. I don't think any other languages have this restriction, so it might be good to align more with convention.

**Comment by novadev94** [comment]
Since the issue's name is about "unused variables", I tried to give it a case-by-case analysis:

1. Unused parameters: Imo, this can be enforced for top-level functions. For anonymous functions, which are usually passed to higher-order functions, the restriction might need to be lifted (in some way), though. Currently, the Helios' way to do it is by introducing sibling functions (for example: `filter`, `filter_by_key` and `filter_by_value`) which might be quite verbose for user-defined functions.

2. Unused variables in assignments: Only useful when we only care about the side effects of a function call. But without `error` being introduced into the language, the only side-effect a function can do is `print`, so not quite valuable at the moment.

3. Unused top-level functions: This is strictly related to the modularity of common functions & types, and is a part of a bigger problem.

4. Unused struct fields & enum variants: Imho, this should be lifted. Many dApps' transactions require a contract to interact with datums (or redeemers) of other contracts (for example, state thread token or https://well-typed.com/blog/2022/08/plutus-initial-conditions/), so having them as "common" types is the only way to go to reduce code duplications. However, the contract might only be interested in some/certain fields, not all of them. Another argument is the encoding of struct/enum in UPLC is order sensitive, so it's reasonable to allow devs to have "holes" in the struct/enum definitions.

**Comment by christianschmitz** [comment]
1,2,3. agree, but could be revisited at a later point in time
4. I agree very strongly, thanks for taking the time to think about this. I've made the changes (v0.7.6)

**Comment by christianschmitz** [comment]
Update:
3 -> the recently implemented modules allow unused top-level statements
1, 2 -> that is the way the language is designed currently. I don't think having a flag for switching between 'dialects' of the language is a good idea. A new issue can be opened if we end up feeling this was a bad language design decision.

I will close this now
