### ISSUE TITLE
Support for Reference Scripts

### ISSUE THREAD

**Issue by gavinharris-dev** [Hyperion-BT/Helios#22]
A major part of the Vasil Hard Fork was the creating of Reference Scripts - CIP33 (https://cips.cardano.org/cips/cip33/).

There are 2 steps to using Reference Scripts:

1. Creating a UTxO on chain with a Reference Script attached. Currently Helios supports this use case perfectly (including calculating the Min UTxO for a TxOutput).
2. Including the UTxO, as a Reference Input on the Transaction (see https://cips.cardano.org/cips/cip32/).

One of the major features that Helios has bought to the table (with its Transaction builder API) is its ability to validate the transaction and calculate the Execution Units for a provided Transaction via the Tx::Finalize function. If we want to implement reference scripts fully we should provide a way for the developer to retain this vital feature while making use of the potential Transaction Cost savings that Reference Scripts could provide.

# Current Art
The existing API allows a developer to attach to a Transaction a Compiled program (Tx::attachScript). There is then logic to ensure that the provided redeemers not only execute correctly but that the correct ExUnits are attached to the Redeemer (itself providing a saving to the Transaction Cost).

# Proposal
Add a new method to the Tx class `Tx::attachRefScript` with a signature such as:

```
Tx:attachRefScript (
  input: TxRefInput,
  script: UplcProgram
)
```
This method should then call `addRefInputs` with the input parameter (functionally reference scripts act the same as any other reference input). 
The 'script' input should be provided to the `TxWitnesses` class so that the script can be made available to the `getScript` method. I am thinking that this should be a separate field to the existing `attachScript` process as we do not want to serialize the script when executing the `toCbor()` (so when building the transaction CBOR output). 

Within the `TxWitnesses`  class we need to extend the `getScript` method so that if a Redeemer points to a reference script then we can provide back the `UplcProgram` to allow for Verification and ExUnit calculation.

Ref: 
https://cips.cardano.org/cips/cip32/
https://cips.cardano.org/cips/cip33/

**Comment by christianschmitz** [comment]
I think your proposal is complete. A separate field in `TxWitnesses` called `refScripts` would indeed need to be defined (and not be part of the serialization).

I would suggest adding an optional `script` argument to `addRefInput` instead as it avoids some ambiguity (people could make the mistake of calling both `addRefInput` and `attachRefScript` for the same ref input.

Another suggestion I would make is attaching a `UplcProgram` instance to a `TxOutput` instead of the bytes directly. I'm unsure if the script would need to be wrapped in a text-envelope (once or twice?) when acting as a reference script. Can you find out how a UplcProgram is serialized into those bytes? (might require some trail-and-error)

I'll get working on the ref input side.

**Comment by christianschmitz** [comment]
I'm going to go ahead and assume ref scripts in `TxOutput` are (de)serialized the same way as regular scripts in `TxWitnesses`.

**Comment by Mercurial** [comment]
Is there any example how to attach a script then reference it in a later transaction?
