### ISSUE TITLE
Optimization: Equal comparisons

### ISSUE THREAD

**Issue by novadev94** [Hyperion-BT/Helios#24]
Currently, all values are compared using `equalData`, which might be inefficient for integers, and even strings & bytestrings.

I've done a small benchmark

`builtin equalsData` uses `1376397` CPU for comparing `(con data #01)` and `(con data #01)`.
`builtin equalsInteger` uses `462033` CPU for comparing `(con integer 10000000000)` and `(con integer 10000000000)`.

**Comment by christianschmitz** [comment]
Currently all  primitive types, excepts booleans (so integers, strings, bytearrays, etc.) are kept as `data`. This approach greatly simplifies the compiler because it allows the type-checking to operate more independently from the code-generation.

Booleans were originally also kept as `data`, but because of the overhead of converting booleans from `data` to primitive (and back) upon each use of a builtin function, it was worth it to treat them in a special way.

So for a fair comparison you must call `builtin unIData` to both arguments of `equalsInteger`.

**Comment by christianschmitz** [comment]
> Btw, do you have plans for expanding the "special treatments" to all UPLC primitive types in the future?

It depends on how Helios is used most commonly. If the primitives are mostly inside containers, then I don't think there is any benefit to having special treatment (booleans are used a lot outside of containers, so it made the most sense). Alternatively if integers/etc. are used a lot in their primitive form, then there could be an advantage. But it is also a lot easier for the optimizer to take care of that automatically for integers/strings/bytearrays, than it is for booleans (because booleans require complex conversion using (un)ConstrData/fstPair/equalsInteger).

**Comment by christianschmitz** [comment]
Latest commit in dev branch has this optimization.

This optimization opportunity is a rare occurrence though, so you probably won't see a great effect

**Comment by christianschmitz** [comment]
Merged as of v0.9.0
