### ISSUE TITLE
Unable to create Transaction with NativeScript

### ISSUE THREAD

**Issue by gavinharris-dev** [Hyperion-BT/helios#78]
I'm using Helios to test a Mint using Native Script (created Transaction using Lucid); however I am unable to parse the Transaction into a Helios Tx `Tx::fromCbor(...)`.

I'm guessing that as I am using a Native Script (not a Plutus Smart Contract) this is not possible with the Helios API?

Transaction CBOR for Reference:
```
84a400818258200000000000000000000000000000000000000000000000000000000000000000000182a300581d603b61a40bc5872219ce830fb9c792d8d53fb87921f590287057e4e3b401821a00152d2ca1581c7292808c44ff8ac77a866a5eadcf8b5463e299e5023a34adc0316269a14a53433030312d3030313001028201d8185847d87b9f9f581c00000000000000000000000000000000000000000000000000000000581c3b61a40bc5872219ce830fb9c792d8d53fb87921f590287057e4e3b40000000000ffff82581d603b61a40bc5872219ce830fb9c792d8d53fb87921f590287057e4e3b41a0090012b021a0002aa6909a1581c7292808c44ff8ac77a866a5eadcf8b5463e299e5023a34adc0316269a14a53433030312d3030313001a101818201818200581c3b61a40bc5872219ce830fb9c792d8d53fb87921f590287057e4e3b4f5f6
```

**Comment by christianschmitz** [comment]
Indeed not yet implemented.

We can do it eventually, but I regret to say this is currently not a priority

**Comment by gavinharris-dev** [comment]
If I can work it out I’ll put together a PR

**Comment by lley154** [comment]
Just my 2 cents, but I also agree that this should be a low priority.  Native scripts were created before plutus was around, so now it really only makes sense to use plutus.  No reason to learn (and support) 2 different types of languages/syntax to do the same thing.

**Comment by gavinharris-dev** [comment]
Is there a Cost difference in using a Plutus Script to validate, say, that a Transaction is signed by a specific Public Key Hash? I cannot find any details on how Native Scripts are priced do not sure on this one!
Fully agree, though, that this should be a low priority, but for an API that supports Cardano it would be good to cover as much of the surface as is reasonable.

**Comment by christianschmitz** [comment]
I'm assuming free. I can't find any cost parameters related to native scripts in the parameter json.

I agree that long term this should be part of the library, it shouldn't be so hard to do. @gavinharris-dev if you have spare time to research this you can go ahead, that's probably the most time-consuming part. The actual implementation should be fairly easy.

**Comment by christianschmitz** [comment]
v0.13.36 adds support for NativeScripts: https://www.hyperion-bt.org/helios-book/api/reference/nativescript.html

The `tx` builder has been changed a bit to allow attaching native scripts (https://www.hyperion-bt.org/helios-book/api/reference/tx.html#attachscript)

Note: you must call tx.attachScript(nativeScript) before adding inputs or minting tokens (this is so we can keep throwing an error if users fail to specify a redeemer for a regular Uplc script).

Testing notes: I've tested the (de)serialization with 5 unit tests, so that should be sufficiently covered. I've also tested that the resulting script addresses are correct. I have however not tested a full tx example. @gavinharris-dev perhaps you could test it the next time you need native scripts?

**Comment by papag00se** [comment]
> Native scripts were created before plutus was around, so now it really only makes sense to use plutus. No reason to learn (and support) 2 different types of languages/syntax to do the same thing.

I don't believe Native Scripts should be considered legacy or otherwise take a backseat to Plutus. They have a simple, straightforward syntax that is easily expressed via JSON. Which makes them very attractive to non-blockchain engineers that Cardano so desperately needs to attract. They are the basis of "multi-sig wallets" and simple minting policies. Why learn/use Plutus (and everything that comes with it) when all that is needed is a signature or two before or after a slot number?

**Comment by lley154** [comment]
no worries, I really don't have a strong opinion here  If folks think Helios should support native scripts that is totally fine and the ability to support native scripts already used/written makes sense.
